variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test_qt5
  - test_qt61
  - test_qt62
  - test_qt66
  - test_qt67
  - test_qt68
  - test_qt69

Test_qt5:
  stage: test_qt5
  image:
    name: "carlonluca/qt-dev:5.15.2"
    entrypoint: [""]
  script:
    - cd LQObjectSerializerTest
    - mkdir build
    - cd build
    - cmake ../qt5
    - make
    - ./LQObjectSerializerTest
    - ./LGithubTestCase

Text_qt61:
  stage: test_qt61
  image:
    name: "carlonluca/qt-dev:6.1.2"
    entrypoint: [""]
  script:
    - cd LQObjectSerializerTest
    - mkdir build
    - cd build
    - cmake ../qt6
    - make
    - ./LQObjectSerializerTest
    - ./LGithubTestCase

Text_qt62:
  stage: test_qt62
  image:
    name: "carlonluca/qt-dev:6.2.3"
    entrypoint: [""]
  script:
    - cd LQObjectSerializerTest
    - mkdir build
    - cd build
    - cmake ../qt6
    - make
    - ./LQObjectSerializerTest
    - ./LGithubTestCase

Test_qt66:
  stage: test_qt66
  image:
    name: "carlonluca/qt-dev:6.6.1"
    entrypoint: [""]
  script:
    - cd LQObjectSerializerTest
    - mkdir build
    - cd build
    - cmake ../qt6
    - make
    - ./LQObjectSerializerTest
    - ./LGithubTestCase

Test_qt67:
  stage: test_qt67
  image:
    name: "carlonluca/qt-dev:6.7.3"
    entrypoint: [""]
  script:
    - cd LQObjectSerializerTest
    - mkdir build
    - cd build
    - cmake ../qt6
    - make
    - ./LQObjectSerializerTest
    - ./LGithubTestCase

Test_qt68:
  stage: test_qt68
  image:
    name: "carlonluca/qt-dev:6.8.1"
    entrypoint: [""]
  script:
    - cd LQObjectSerializerTest
    - mkdir build
    - cd build
    - cmake ../qt6
    - make
    - ./LQObjectSerializerTest
    - ./LGithubTestCase

Test_qt69:
  stage: test_qt69
  image:
    name: "carlonluca/qt-dev:6.9.1"
    entrypoint: [""]
  script:
    - cd LQObjectSerializerTest
    - mkdir build
    - cd build
    - cmake ../qt6
    - make
    - ./LQObjectSerializerTest
    - ./LGithubTestCase