image:
  name: "carlonluca/qt-dev:5.15.2"
  entrypoint: [""]

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

# Job 1
Test:
  stage: test
  script:
    - cd LQObjectSerializerTest
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./LQObjectSerializerTest
    - ./LGithubTestCase
